### ISSUE TITLE
Support tedious 2.0.1?

### ISSUE THREAD

**Issue by vangorra** [tediousjs/tedious-connection-pool#43]
This is a feature request. It would be nice if this project supported a modern version of tedious.

**Comment by jschell12** [comment]
So I added a pull request of my own to update the native [tedious](https://github.com/tediousjs/tedious) dependency to 2.1.1.

**Comment by wallali** [comment]
Hi, Any reason why these changes have not been accepted by the Author?

**Comment by 700software** [comment]
The author is alive !!

Maybe we can deprecate tedious-connection-pool2?
